### ISSUE TITLE
Request for mocks for unit-tests

### ISSUE THREAD

**Issue by batbrain9392** [ng-web-apis/common#22]
# 🚀 Feature request

Could we get mocks like how you've provided it in your universal package? Ref - [link](import '@ng-web-apis/universal/mocks')

`import '@ng-web-apis/universal/mocks';`

**Comment by waterplea** [comment]
Hey 👋 You mean like for testing with jest? I believe you can already just use mocks from universal, as well as tokens from it. Please let me know if that works for you.

**Comment by batbrain9392** [comment]
For Jasmine/Karma. But will check with the mocks from universal.

But the mocks and tokens can be taken from universal, why maintain 2 repos with the same functionalities?

**Comment by waterplea** [comment]
This library is just a library of token so you make your apps without any direct access to global entities, because they might not be available in some environments. Universal package is the package of substitutes for those tokens for server side which also might work in other environments where they are missing. For example jest testing is a lot like universal as it is also emulated DOM. Is Jasmine/Karma you don't need mocks, because tokens are available as is. But you can easily mock them with spies etc. in unit tests.

**Comment by batbrain9392** [comment]
@waterplea Do you have an example of how these tokens can be mocked in Jasmine/Karma unit tests?

**Comment by waterplea** [comment]
When you configure `TestBed` you can add to providers something like this:
```
{
  provide: WINDOW,
  useValue: { 
    matchMedia(query: string): boolean {
      return query === '(min-width: 400px)';
    }
  }
}
```
for example, if you want to run your code depends on screen size by running `window.matchMedia` and you want to test particular configuration
